### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by jzelinskie** [pyapi-gitlab/pyapi-gitlab#126]
Would you consider providing an alternate license of `pyapi-gitlab` so that it can be linked with non-free software?

I would honestly prefer something like MIT, but if you want to keep copyleft, [the MPL](https://www.mozilla.org/MPL/) is a popular license that is a source-level copyleft, thus requiring changes to be provided back to the original author, but still allows you to link to non-free software.

**Comment by Itxaka** [comment]
Hey @jzelinskie , why would be the reasoning for this change?

I been thinking about this for a long time actually. At first I went with the GPL3 because it was ok, but the more I went on the innards of it the more I feel like its not the rigth choice for any project to grow.

Would something like the Apache license work for whatever your needs are?

**Comment by jzelinskie** [comment]
Apache sounds great -- we'd like to use this library to add GitLab support to Quay.io.
It really sucks because both python wrappers for GitLab are GPLv3.

**Comment by Itxaka** [comment]
Great! Im checking to do a hotfix for #125 so Ill probably do the change of the License at the same time a release a new version to pypi.

**Comment by jzelinskie** [comment]
Awesome! Thanks a bunch.
