### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by Itxaka** [pyapi-gitlab/pyapi-gitlab#169]
Unfortunately I dont have enough time to keep up with the API random changes from Gitlab, nor with their ability to break the API every minor release. I transfered the library into its own organization, if you are interested in maintaining the lib, just drop me a line and Ill add you to the org. Thanks!

**Comment by ssbarnea** [comment]
I am interested about performing some maintenance on it as I just raised few serious bugs and I would prefer to fix them instead of having to go around them, see #170 and #171 

I am maintaining several python libraries myself and all of them are owned by an organization named PyContribs -- the reson is clear: just to avoid reaching a point when a module becomes abandonware because it had a single author which left for one reason or another. 

Have a look https://github.com/pycontribs

So for start please just give me full access to the repository so I can fix those and get the other pull requests merged. Later, if you want, we can move the project inside the PyContribs organization.

**Comment by Itxaka** [comment]
@ssbarnea I didnt knew about pycontribs, sounds like a great idea! Ill add you to the org right away and thnks for stepping up.

**Comment by ssbarnea** [comment]
Thanks! Problem fixed but this does not mean that other contributors are not welcomed!
