### ISSUE TITLE
Params page and per_page

### ISSUE THREAD

**Issue by jirihnidek** [pyapi-gitlab/pyapi-gitlab#37]
Hi,
methods like git.getprojects() git.getusers(), etc. have parameters `page=1` and `per_page=20`. These parameters are not in documentation and it can influence behavior of Python script a lot. It means that your script will work for few projects, users, groups, but when you go to the production, then it will stop to work, because you have hundreds of users, projects, etc.

I vote to remove/modify these parameter. If default parameter values would be `None`, then these methods would just get all projects, all users, etc., because it is thing, you usually want.

Cheers,
Jiri

**Comment by Itxaka** [comment]
@sag47 introduced those params, maybe there was a reson for those limits?

**Comment by jirihnidek** [comment]
`page=1` and `per_page=20` are default values from GitLab API: http://api.gitlab.org/

**Comment by samrocketman** [comment]
@jirihnidek you are correct; those are the defaults from the GitLab API.  So even if you set them to `None` the API will behave with those defaults.  It was an odd behavior I discovered and it took a long time to troubleshoot (see #18, #22).  This way, by explicitely stating pagination the developer against the API doesn't have to dig very deep to find those values.  

If you'd like to see an example for how I'm using it see [gitlab-mirrors snippet](https://github.com/sag47/gitlab-mirrors/blob/master/lib/manage_gitlab_project.py#L59-L67).

Technically it's not undocumented, in python interactive interpreter if you type...

```
import gitlab
dir(gitlab.Gitlab)
help(gitlab.Gitlab.getProjects)
```

You'll see that it is documented.  I guess you're referring to the online documentation.  It seems @Itxaka already has an issue open for that #21.  Perhaps it would be good to mention pagination defaults as well as a pagination example for how to use it in the online documentation.

**Comment by Itxaka** [comment]
Yeah, sorry guys, documentation is BORING!

I'l try to keep it updated for this weekend...hopefully :beer:

**Comment by jirihnidek** [comment]
Hi,
I understand, why GitLab API uses `page` an `per_page` and it makes sense to have it in GitLab Python module too, but most developers using this module will try to get all projects, all groups, etc. with own code. Philosophy of Python is to do things once and thus it would make sense to add such code to the module.

**Comment by Itxaka** [comment]
@jirihnidek if we use None as parameter, wouldn't gitlab answer with 20 per_page anyway? In that case we should use a huge number for it, which is worst in my opinion.

**Comment by samrocketman** [comment]
@Itxaka @jirihnidek as per the Gitlab documentation the max number which `per_page` can be set is `100`.  That being said are you saying it should return all values by default no matter what unless the developer explicitly states to paginate?

i.e. implement something like this when the parameter values equal `None`?  Sort of like this.... https://gist.github.com/sag47/6937133

If that's the case I think that would be a bad practice I think pagination on by default is best in my opinion.  It allows developers to have good performing interactions with the API's by default.  Sure it's fine if you have a few dozen projects, a few hundred, or even a few thousand.... but what if a developer has a few million projects?  What about several million users?  I **don't** think non-pagination should be the default behavior of this API library.

I think it would be better for this library to _document examples_ of how a Python developer would utilize pagination rather then giving them every project by default, letting them trip, and figure out they need pagination.  The pagination is designed built-in so that it can scale.

**Comment by jirihnidek** [comment]
Ok ok :-), when it will be well documented, then I don't have any problem with `per_page` and `page`. Closing this issue.

**Comment by Itxaka** [comment]
@jirihnidek I'll reopen it so I don't forget to add it to docs :+1:
